version: '3.3'

services:
  web:
    build: .
    command: python3 -m flask run --cert=src/diabeticare/certs/cert.pem --key=src/diabeticare/certs/key.pem --host=0.0.0.0 --port=8000
    volumes:
      - .:/diabeticare-server-docker/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=I5Kw3jesAWDO2NsiMAyt2g
      - POSTGRES_DB=default

volumes:
  postgres_data:
